# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f28b77009b0b1fa1b59fa4dc4a9c619ad102bcb9171185fb9ca9dc90e28c26dc6bc622ad66f75d98765bfd6e4b07259c16799db6125dae6fc8b7cf46664b52a1

test:
  secret_key_base: c4ebee571d02a9b20562e1eebdabe660d040399934fbefd6282c2e58df35136020033715c8e4f4003a829bead1d044c01b1327832e2eb5689210096b40b01e78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
